version: '3.8'

services:
  web:
    image: nginx-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  networks:
    app-network:
      driver: bridge
